<a href="https://colab.research.google.com/github/aryanmanlol/Python/blob/main/Numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
from numpy import random

In [ ]:
#1



In [ ]:
a=random.randint(10,100,size=(3,5,3))
a

array([[[68, 18, 91],
        [25, 53, 69],
        [55, 47, 98],
        [18, 39, 22],
        [77, 89, 61]],

       [[63, 44, 13],
        [80, 46, 30],
        [36, 26, 17],
        [66, 78, 23],
        [87, 54, 94]],

       [[28, 21, 85],
        [57, 48, 54],
        [66, 63, 97],
        [26, 98, 52],
        [18, 67, 84]]])

In [ ]:
#2
s=int(input("size of list"))
list=[]
for i in range(0,s):
  l=int(input("enter elements"))
  list.append(l)

a=np.array(list)
newarr=a.reshape(2,-1)



size of list6
enter elements1
enter elements2
enter elements3
enter elements4
enter elements5
enter elements6


In [ ]:
print(newarr)

[[1 2 3]
 [4 5 6]]


In [ ]:
p=int(input("lower range"))
q=int(input("higher range"))
m=int(input("enter rows"))
n=int(input("enter columns"))
random=random.randint(p,q,size=(m,n))
print(random)

lower range3
higher range80
enter rows4
enter columns5
[[64  3 23 32 16]
 [14 16 36 77 41]
 [37 24 19 42 40]
 [33 18 20 51 14]]


In [ ]:
print(random.ndim)

2


In [ ]:
print(random.size)

20


In [ ]:
arr=random.reshape(5,-1)

In [ ]:
arr

array([[64,  3, 23, 32],
       [16, 14, 16, 36],
       [77, 41, 37, 24],
       [19, 42, 40, 33],
       [18, 20, 51, 14]])

In [ ]:
array=np.array([[2,3,4,5,6,7],[3,90,10,14,7,8]])
array[1,1:4]

array([90, 10, 14])

In [ ]:
arr=np.sort(array)

In [ ]:
arr

array([[ 2,  3,  4,  5,  6,  7],
       [ 3,  7,  8, 10, 14, 90]])

In [ ]:
import pandas as pd

In [ ]:
dist={1:["golu","boob"],2:["ektu",0],3:["patootu",0]}
d=pd.DataFrame(dist)
print(d)

      1     2        3
0  golu  ektu  patootu
1  boob     0        0


In [ ]:
list1=[2,3,4,5,6,7]
list2=[4,5,6,7,8,9]
list3=[10,20,30,40,50,60]
df=pd.DataFrame([list1,list2,list3])
df

0   1   2   3   4   5
0   2   3   4   5   6   7
1   4   5   6   7   8   9
2  10  20  30  40  50  60

from matplotlib import pyplot as plt
df[0].plot(kind='hist', bins=20, title=0)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df[1].plot(kind='hist', bins=20, title=1)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df[2].plot(kind='hist', bins=20, title=2)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df[3].plot(kind='hist', bins=20, title=3)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x=0, y=1, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x=1, y=2, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x=2, y=3, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x=3, y=4, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[0]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 0}, axis=1)
              .sort_values(0, ascending=True))
  xs = counted[0]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values(0, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(0)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[1]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 1}, axis=1)
              .sort_values(1, ascending=True))
  xs = counted[1]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values(1, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(1)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[2]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 2}, axis=1)
              .sort_values(2, ascending=True))
  xs = counted[2]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values(2, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(2)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[3]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 3}, axis=1)
              .sort_values(3, ascending=True))
  xs = counted[3]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values(3, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(3)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
df[0].plot(kind='line', figsize=(8, 4), title=0)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df[1].plot(kind='line', figsize=(8, 4), title=1)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df[2].plot(kind='line', figsize=(8, 4), title=2)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df[3].plot(kind='line', figsize=(8, 4), title=3)
plt.gca().spines[['top', 'right']].set_visible(False)

NameError: name 'iris' is not defined